{"name": "test_get_json_failure", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'aiohttp.client_exceptions.ClientResponseError'>", "trace": "@pytest.mark.asyncio\n    async def test_get_json_failure():\n        url = \"https://jsonplaceholder.typicode.com/todos/invalid\"\n>       with pytest.raises(aiohttp.ClientResponseError):\nE       Failed: DID NOT RAISE <class 'aiohttp.client_exceptions.ClientResponseError'>\n\ntests\\test_app.py:15: Failed"}, "start": 1702545439471, "stop": 1702545439927, "uuid": "e3feed03-206b-4414-82e5-c836dacd10c2", "historyId": "4ae280fb04efa43257b4a1307274006f", "testCaseId": "4ae280fb04efa43257b4a1307274006f", "fullName": "tests.test_app#test_get_json_failure", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_app"}, {"name": "host", "value": "DESKTOP-RKLJ7AP"}, {"name": "thread", "value": "5748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_app"}]}